#!/usr/bin/env bash
# abi-install-selfupdate.sh — one-shot install of the secure ABI self-update
# mechanism on a VM. Drops the root wrapper + public key + sudoers rule so the
# agent service user can trigger updates through the locked-down wrapper only.
#
# Run as root. Idempotent. Used by BOTH the fresh-deploy runbook and a one-time
# install on already-deployed VMs (Snowbytes/customers, after sign-off).
#
# Usage:
#   sudo ./scripts/abi-install-selfupdate.sh                     # detect service user
#   sudo ./scripts/abi-install-selfupdate.sh --user snowbytes
#   sudo ./scripts/abi-install-selfupdate.sh --source /tmp/artifacts --user brian
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SOURCE_DIR="${SCRIPT_DIR}"          # where abi-update-trigger/.sh + abi-release.pub live
SERVICE_USER=""
SERVICE_NAME="hermes-gateway"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source) SOURCE_DIR="$2"; shift 2 ;;
    --user) SERVICE_USER="$2"; shift 2 ;;
    --service) SERVICE_NAME="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

[ "$(id -u)" -eq 0 ] || { echo "Run as root (sudo)." >&2; exit 1; }
[ -f "$SOURCE_DIR/abi-update-trigger" ] || { echo "Missing $SOURCE_DIR/abi-update-trigger" >&2; exit 1; }
[ -f "$SOURCE_DIR/abi-update.sh" ]      || { echo "Missing $SOURCE_DIR/abi-update.sh" >&2; exit 1; }

# Detect the service user if not given: whoever runs the system gateway service.
if [ -z "$SERVICE_USER" ]; then
  if systemctl list-unit-files 2>/dev/null | grep -q "^$SERVICE_NAME\.service"; then
    SERVICE_USER="$(systemctl show "$SERVICE_NAME" -p User --value 2>/dev/null | head -1)"
  fi
fi
[ -n "$SERVICE_USER" ] || { echo "Could not detect service user. Pass --user <name>." >&2; exit 1; }
id "$SERVICE_USER" >/dev/null 2>&1 || { echo "User '$SERVICE_USER' does not exist." >&2; exit 1; }

echo "=== ABI self-update install ==="
echo "Service user: $SERVICE_USER   Service: $SERVICE_NAME"
echo "Source dir:   $SOURCE_DIR"
echo ""

# 1. minisign (verify dependency). Available in Debian 13 main.
if ! command -v minisign >/dev/null 2>&1; then
  echo "Installing minisign..."
  apt-get update -qq >/dev/null 2>&1 || true
  apt-get install -y minisign
fi

# 2. /opt/abi-tools — root:root, NOT group-writable (the whole trust anchor).
mkdir -p /opt/abi-tools /opt/abi-tools/backups
chown root:root /opt/abi-tools /opt/abi-tools/backups
chmod 0755 /opt/abi-tools /opt/abi-tools/backups

# 3. Drop artifacts. chattr -i first if a prior install made them immutable.
install_immutable() {  # $1=dest $2=src $3=mode
  local dest="$1" src="$2" mode="$3"
  chattr -i "$dest" 2>/dev/null || true
  install -m "$mode" -o root -g root "$src" "$dest"
  chattr +i "$dest"
}

echo "Installing updater + wrapper + pubkey..."
install -m 0755 -o root -g root "$SOURCE_DIR/abi-update.sh" /opt/abi-tools/abi-update.sh
install_immutable /opt/abi-tools/abi-update-trigger "$SOURCE_DIR/abi-update-trigger" 0755
if [ -f "$SOURCE_DIR/abi-release.pub" ]; then
  install_immutable /opt/abi-tools/abi-release.pub "$SOURCE_DIR/abi-release.pub" 0644
else
  echo "WARNING: no abi-release.pub in $SOURCE_DIR — signature verification will fail until one is shipped." >&2
fi

# 4. Audit log — append-only (+a), root-owned. Hash-chained by the wrapper.
touch /opt/abi-tools/update-audit.log
chown root:root /opt/abi-tools/update-audit.log
chmod 0600 /opt/abi-tools/update-audit.log
chattr -a /opt/abi-tools/update-audit.log 2>/dev/null || true
chattr +a /opt/abi-tools/update-audit.log

# 5. sudoers drop-in: NOPASSWD on the wrapper ONLY, clean env, no SETENV.
#    One rule per service user (supports multi-agent boxes by repeating --user).
SUDOERS=/etc/sudoers.d/abi-update
umask 022
{
  echo "# ABI agent self-update — generated by abi-install-selfupdate.sh"
  echo "Defaults:$SERVICE_USER env_reset, secure_path=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", use_pty, !setenv"
  echo "$SERVICE_USER ALL=(root) NOPASSWD: /opt/abi-tools/abi-update-trigger"
} > "$SUDOERS"
chmod 0440 "$SUDOERS"

# 6. Validate sudoers before trusting it.
if ! visudo -cf "$SUDOERS" >/dev/null 2>&1; then
  echo "FATAL: generated sudoers file is invalid — removing it." >&2
  rm -f "$SUDOERS"
  exit 1
fi
visudo -c >/dev/null 2>&1 || { echo "FATAL: visudo -c failed (global). Aborting." >&2; exit 1; }

echo ""
echo "=== Install OK ==="
echo "Verify (as $SERVICE_USER):  sudo -n /opt/abi-tools/abi-update-trigger check"
echo "Wrapper immutable:          lsattr /opt/abi-tools/abi-update-trigger"
echo "Pubkey immutable:           lsattr /opt/abi-tools/abi-release.pub"
echo "Audit append-only:          lsattr /opt/abi-tools/update-audit.log"
echo ""
echo "NOTE: this only grants the privilege path. For it to be a TRUE privilege"
echo "boundary, $SERVICE_USER must NOT be in the 'docker' group and must NOT have"
echo "blanket NOPASSWD sudo (docker socket = root). Review: 'id $SERVICE_USER' and"
echo "'sudo -ln -U $SERVICE_USER'."
